# Site settings
title: Sparkle Visualization
description: > 
  Data Visualization with d3 and scala. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://mighdoll.github.io/sparkle"
twitter_username: nest
github_username:  mighdoll

# Build settings
markdown: kramdown
