# Site settings
title: Sparkle Visualization
email: lee@underneath.ca
description: > 
  Data Visualization with d3 and scala. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://mighdoll.github.io/sparkle"
twitter_username: mighdoll
github_username:  mighdoll

# Build settings
markdown: kramdown
